# import = ["/home/khainguyen/.config/alacritty/themes/themes/onedark.toml"]

[env]
TERM = "tmux-256color"

[colors.primary]
background = '#171d23'
# background = '#171d23'
foreground = '#abb2bf'

[colors.normal]
black   = '#1e2127'
red     = '#e06c75'
green   = '#98c379'
yellow  = '#d19a66'
blue    = '#61afef'
magenta = '#c678dd'
cyan    = '#56b6c2'
white   = '#abb2bf'

[colors.bright]
black   = '#5c6370'
red     = '#e06c75'
green   = '#98c379'
yellow  = '#d19a66'
blue    = '#61afef'
magenta = '#c678dd'
cyan    = '#56b6c2'
white   = '#ffffff'

[font]
size = 10

[font.bold]
family = "JetBrainsMonoNL Nerd Font"
style = "Bold"

[font.bold_italic]
family = "JetBrainsMonoNL Nerd Font"
style = "Bold Italic"

[font.italic]
family = "JetBrainsMonoNL Nerd Font"
style = "Italic"

[font.normal]
family = "JetBrainsMonoNL Nerd Font"
style = "Regular"

[[keyboard.bindings]]
action = "SpawnNewInstance"
key = "Return"
mods = "Super|Shift"

[scrolling]
history = 100000
multiplier = 3

[selection]
save_to_clipboard = false

[shell]
program = "/usr/bin/tmux"

[window]
decorations = "none"
decorations_theme_variant = "Dark"
opacity = 0.99

[window.class]
general = "Alacritty"
instance = "Alacritty"

[window.dimensions]
columns = 110
lines = 34

[window.padding]
x = 0
y = 0
