import:
- ~/.config/alacritty/themes/themes/one-dark.yaml

env:
  TERM: tmux-256color

window:
  decorations: none
  decorations_theme_variant: Dark
  padding:
    x: 0
    y: 0
  dimensions:
    columns: 110
    lines: 34
  class:
    instance: Alacritty
    general: Alacritty
  opacity: 0.98

scrolling:
  history: 100000
  multiplier: 3


font:
  size: 10
  normal:
    family: JetBrainsMonoNL Nerd Font
    style:  Regular
  bold:
    family: JetBrainsMonoNL Nerd Font
    style:  Bold
  italic:
    family: JetBrainsMonoNL Nerd Font
    style:  Italic
  bold_italic:
    family: JetBrainsMonoNL Nerd Font
    style: Bold Italic

# draw_bold_text_with_bright_colors: true

selection:
  save_to_clipboard: false

key_bindings:
  - { key: Return, mods: Super|Shift, action: SpawnNewInstance }

shell:
  program: /usr/bin/tmux
  # args:
  #   - -l
  #   - -c
  #   - "tmux"
