# import = ["/home/khainguyen/.config/alacritty/themes/themes/onedark.toml"]

# [env]
# TERM = "xterm-256color"

[colors.primary]
background = "0x27292E"
foreground = "0xe2e2e3"

[colors.normal]
black = "0x181819"
red = "0xfc5d7c"
green = "0x9ed072"
yellow = "0xe7c664"
blue = "0x76cce0"
magenta = "0xb39df3"
cyan = "0xf39660"
white = "0xe2e2e3"


[colors.bright]
black = "0x7f8490"
red = "0xfc5d7c"
green = "0x9ed072"
yellow = "0xe7c664"
blue = "0x76cce0"
magenta = "0xb39df3"
cyan = "0xf39660"
white = "0xe2e2e3"

[font]
size = 10.5

[font.bold]
family = "JetBrainsMonoNL Nerd Font"
style = "Bold"

[font.bold_italic]
family = "JetBrainsMonoNL Nerd Font"
style = "Bold Italic"

[font.italic]
family = "JetBrainsMonoNL Nerd Font"
style = "Italic"

[font.normal]
family = "JetBrainsMonoNL Nerd Font"
style = "Regular"

[[keyboard.bindings]]
action = "SpawnNewInstance"
key = "Return"
mods = "Super|Shift"

[scrolling]
history = 100000
multiplier = 3

[selection]
save_to_clipboard = false

[shell]
program = "wsl.exe -d Arch -u khainguyen --cd ~ tmux"

[window]
# decorations = "none"
decorations_theme_variant = "Dark"
# opacity = 0.98

[window.class]
general = "Alacritty"
instance = "Alacritty"

[window.dimensions]
columns = 110
lines = 34

[window.padding]
x = 0
y = 0
